name: "Setup and Install Node.js"
description: "Checkouts code, sets up Node.js and installs dependencies"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: ".nvmrc"
        registry-url: "https://registry.npmjs.org/"
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        key: npm-${{ hashFiles('./package-lock.json') }}
        path: ~/.npm
        restore-keys: npm-
    - name: Install dependencies
      shell: bash
      run: npm ci --no-audit --no-progress --prefer-offline
