name: 'Setup and Install Node.js'
description: 'Checkouts code, sets up Node.js and installs dependencies'
inputs:

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3.6.0
      with:
        persist-credentials: false
        ref: ${{ github.event.pull_request.head.sha || github.sha }}
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
        registry-url: 'https://registry.npmjs.org/'
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        key: npm-${{ hashFiles('./package-lock.json') }}
        path: ~/.npm
        restore-keys: npm-
    - name: Install dependencies
      run: npm ci --no-audit --no-progress --prefer-offline